services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    image: ${DOCKER_IMAGE}
    container_name: server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      JPA_HIBERNATE_DDL: update
      DATABASE_URL: jdbc:mysql://localhost:3306/mainDB
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: 1234
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
