services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: "unless-stopped"

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend


  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]


  app:
    image: jhsong8034/tutorial:pillyohae
    container_name: server
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      JPA_HIBERNATE_DDL: ${JPA_HIBERNATE_DDL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
    driver: bridge
