services:
  rabbitmq:
    image: rabbitmq:3.0-management
    container_name: rabbitmq
    restart: "unless-stopped"
    ports:
      - "5672:5672"     # AMQP 기본 포트
      - "15672:15672"   # 웹 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - payment
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # 데이터 영속화


  app:
    image: ${DOCKER_HUB_REPOSITORY}:payment
    container_name: server
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      JPA_HIBERNATE_DDL: ${JPA_HIBERNATE_DDL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - payment

volumes:
  rabbitmq_data:

networks:
  payment:
    driver: bridge
