name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Clean Gradle cache
        run: |
          ./gradlew clean --no-daemon
          ./gradlew --stop
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf .gradle/
          find . -name "build" -type d -exec rm -rf {} + || true

      - name: Build with Gradle
        run: |
          ./gradlew bootJar --refresh-dependencies --no-daemon --stacktrace --info

      - name: Docker Build and Push main server image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker build --no-cache -t "$DOCKER_HUB_REPOSITORY":pillyohae -f main-server/Dockerfile ./main-server
          docker push "$DOCKER_HUB_REPOSITORY":pillyohae

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DOCKER_HUB_REPOSITORY=${{ secrets.DOCKER_HUB_REPOSITORY }}
          DATABASE_USERNAME=${{ secrets.DATABASE_ID }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JPA_HIBERNATE_DDL=${{ secrets.JPA_HIBERNATE_DDL }}
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
          SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          TZ=Asia/Seoul
          EOF

      - name: Copy env files to main server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          source: "./.env"
          target: "~/app/"

      - name: Copy docker-compose file to main server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          source: "./main-server/docker-compose.yml"
          target: "~/app/docker-compose.yml"

      - name: SSH into server and deploy main server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            echo "=== 기존 파일 정리 ==="
            sudo rm -rf ~/app/*
            echo "=== Docker 로그인 ==="
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "=== 파일 복사 대기 ==="
            sleep 5
            echo "=== 파일 확인 ==="
            ls -la ~/app/
            cat ~/app/docker-compose.yml || echo "docker-compose.yml not found"
            cat ~/app/.env
            echo "=== Docker Compose 실행 ==="
            cd ~/app
            sudo docker compose down || true
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans